private ["_vehicle","_class","_maxMagazines","_maxWeapons","_maxBackpacks","_magazineCount","_weaponsCount","_backpackCount"];
disableUserInput true;
player playActionNow "PutDown";
_vehicle = _this select 3;
_class = typeOf _vehicle;
_maxMagazines =    getNumber (configFile >> "CfgVehicles" >> _class >> "transportMaxMagazines");
_maxWeapons =    getNumber (configFile >> "CfgVehicles" >> _class >> "transportMaxWeapons");
_maxBackpacks =    getNumber (configFile >> "CfgVehicles" >> _class >> "transportmaxbackpacks");
_magazineCount_raw = getMagazineCargo _vehicle;
_weaponsCount_raw = getWeaponCargo _vehicle;
_backpackCount_raw = getBackpackCargo _vehicle;
_magazineCount = (_magazineCount_raw select 1) call vehicle_gear_count;
_weaponsCount = (_weaponsCount_raw select 1) call vehicle_gear_count;
_backpackCount = (_backpackCount_raw select 1) call vehicle_gear_count;
TitleText [format[("Magazine: %1 / %2 - Weapons/Tools: %3 / %4 - Backpacks: %5 / %6"),_magazineCount,_maxMagazines,_weaponsCount,_maxWeapons,_backpackCount,_maxBackpacks], "PLAIN DOWN"];
sleep 4;
disableUserInput false;