GearAdd = (vehicle player);
GearAdd addMagazine 'HandGrenade_West';
GearAdd addMagazine 'HandGrenade_West';
GearAdd addMagazine 'HandGrenade_West';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap'; 
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addBackpack 'DZ_Backpack_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemWire', 6];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemSandbag', 6];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGeneric', 4];
