GearAdd = (vehicle player);
GearAdd addWeapon 'Binocular_Vector';
GearAdd addWeapon 'NVGoggles';
GearAdd addWeapon 'ItemGPS';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'ItemMatchbox';
GearAdd addWeapon 'ItemEtool';
GearAdd addWeapon 'ItemToolbox';
GearAdd addWeapon 'ItemCrowbar';
GearAdd addWeapon 'ItemFlashlightRed';
GearAdd addWeapon 'ItemRadio';