GearAdd = (vehicle player);
GearAdd addMagazine 'FoodSteakCooked';
GearAdd addMagazine 'ItemAntibiotic';
GearAdd addMagazine 'ItemHeatPack';
GearAdd addMagazine 'ItemSodaMdew';
GearAdd addMagazine 'ItemHeatPack';
GearAdd addMagazine 'ItemMorphine';
GearAdd addMagazine 'ItemBloodbag';
GearAdd addMagazine 'ItemPainkiller'; 
GearAdd addMagazine 'ItemEpinephrine';
GearAdd addMagazine 'ItemSodaMdew';
GearAdd addMagazine 'FoodSteakCooked';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addBackpack 'DZ_Backpack_EP1';
(Unitbackpack GearAdd) addMagazineCargo ['ItemBloodbag', 4];
(Unitbackpack GearAdd) addMagazineCargo ['ItemHeatPack', 6];
(Unitbackpack GearAdd) addMagazineCargo ['ItemSodaPepsi', 5];
(Unitbackpack GearAdd) addMagazineCargo ['FoodSteakCooked', 3];
(Unitbackpack GearAdd) addMagazineCargo ['ItemMorphine', 2];