GearAdd = (vehicle player);
GearAdd addMagazine 'PartWheel';
GearAdd addMagazine 'PartWheel';
GearAdd addMagazine 'PartWheel';
GearAdd addMagazine 'PartWheel';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addBackpack 'DZ_Backpack_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartEngine', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemJerrycan', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGeneric', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartVRotor', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartFueltank', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGlass', 1];